# Generated by Django 5.2.3 on 2025-08-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='institution',
        ),
        migrations.AlterField(
            model_name='batch',
            name='fee_structure',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
