# Generated by Django 5.2.3 on 2025-08-04 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_remove_batch_institution_alter_batch_fee_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testApp.institution'),
            preserve_default=False,
        ),
    ]
