# Generated by Django 5.2.3 on 2025-08-04 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_batch_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='fee_structure',
        ),
        migrations.AlterField(
            model_name='studentbatch',
            name='joined_date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 8, 4, 4, 10, 46, 916506, tzinfo=datetime.timezone.utc)),
        ),
    ]
