# Generated by Django 5.2.3 on 2025-08-04 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0004_remove_batch_fee_structure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbatch',
            name='joined_date',
            field=models.DateField(default=datetime.datetime(2025, 8, 4, 4, 32, 38, 328079, tzinfo=datetime.timezone.utc)),
        ),
    ]
