# Generated by Django 5.2.3 on 2025-08-04 10:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0005_alter_studentbatch_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbatch',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
