# Generated by Django 5.2.3 on 2025-07-23 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='authentication.permission'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.usertype'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
