# Generated by Django 5.2.3 on 2025-07-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='permissions',
        ),
        migrations.AddField(
            model_name='usertype',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='authentication.permission'),
        ),
    ]
