# Generated by Django 5.2.3 on 2025-07-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_permission',
            field=models.ManyToManyField(blank=True, null=True, to='authentication.permission'),
        ),
    ]
