# Generated by Django 5.2.3 on 2025-07-25 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='institution',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
