# Generated by Django 5.2.3 on 2025-08-01 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeapp', '0002_remove_batch_institution_delete_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Amount')], max_length=30)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=10)),
                ('is_upfront', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FeeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_before_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('due_type', models.CharField(choices=[('fixed', 'Fixed'), ('joining_date', 'Joining_Date')], max_length=50)),
                ('fixed_due_date', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insatllment_choice', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('custom', 'Custom')], max_length=30)),
                ('days', models.PositiveIntegerField(blank=True, null=True)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeapp.feestructure')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentBatchFeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.AddField(
            model_name='feecomponent',
            name='fee_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeapp.feestructure'),
        ),
        migrations.AddField(
            model_name='discount',
            name='feestructure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeapp.feestructure'),
        ),
        migrations.AddField(
            model_name='installmentdetails',
            name='installment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeapp.installmenttype'),
        ),
        migrations.AddField(
            model_name='payment',
            name='installment_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeapp.installmentdetails'),
        ),
        migrations.AddField(
            model_name='studentbatchfeedetails',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeapp.discount'),
        ),
        migrations.AddField(
            model_name='studentbatchfeedetails',
            name='selected_installment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeapp.installmenttype'),
        ),
        migrations.AddField(
            model_name='feenotification',
            name='student_batch_fee_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feeapp.studentbatchfeedetails'),
        ),
    ]
