# Generated by Django 5.2.3 on 2025-08-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeapp', '0003_discount_feecomponent_feenotification_feestructure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='batch',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
