# Generated by Django 5.2.3 on 2025-08-05 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeapp', '0004_feestructure_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='feestructure',
        ),
        migrations.RemoveField(
            model_name='installmenttype',
            name='fee_structure',
        ),
        migrations.AddField(
            model_name='studentbatchfeedetails',
            name='fee_structure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feeapp.feestructure'),
        ),
        migrations.AddField(
            model_name='studentbatchfeedetails',
            name='student_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
