# Generated by Django 5.2.3 on 2025-08-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeapp', '0005_remove_discount_feestructure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feecomponent',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
