# Generated by Django 5.2.3 on 2025-08-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeapp', '0006_alter_feecomponent_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentdetails',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
